### ISSUE TITLE
`/_global/search` already exists

### ISSUE THREAD

**Issue by dcsaszar** [Scrivito/example_app#33]
Hello @cedrics,

we ran into the following issue with a fresh trial CMS. We haven't reproduced the exact steps, but the testers believe they just followed the documentation on getting the example app to work.
The quick solution was to delete the CMS and create a fresh one.

```
example_app-master test$ bundle exec rake scrivito:migrate scrivito:migrate:publish

== 20141127102237 GenerateSeedContentMigration: migrating =====================
rake aborted!
Scrivito::ClientError: invalid value for key '_path' (already_exists): /_global/search
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/cms_rest_api.rb:137:in `handle_response'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/cms_rest_api.rb:120:in `response_for_request_cms_api'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/cms_rest_api.rb:89:in `request_cms_api'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/cms_rest_api.rb:46:in `post'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/workspace.rb:149:in `public_send'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/workspace.rb:149:in `api_request'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/basic_obj.rb:126:in `create'
/Users/test/dev/example/example_app-master/scrivito/migrate/20141127102237_generate_seed_content_migration.rb:28:in `create_homepage'
/Users/test/dev/example/example_app-master/scrivito/migrate/20141127102237_generate_seed_content_migration.rb:3:in `up'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migration.rb:24:in `block in migrate'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migration.rb:24:in `migrate'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migrator.rb:47:in `block (2 levels) in migrate'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migrator.rb:46:in `each'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migrator.rb:46:in `block in migrate'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/workspace.rb:258:in `as_current'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/scrivito/migrations/migrator.rb:45:in `migrate'
/Users/test/.rvm/gems/ruby-2.2.1/gems/scrivito_sdk-0.66.0/lib/tasks/migration.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => scrivito:migrate
(See full trace by running task with --trace)
```

**Comment by cedrics** [comment]
#32 makes clear to the user why the error happened. I will talk to Jens if I can nail down the content got into the tenant but I am guessing he ran the install generator previously.
